runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
- url: /login
  script: main.app
- url: /admin
  script: main.app
  login: admin
- url: /.*
  script: main.app
  login: required
